image:
  file: .devcontainer/gitpod.Dockerfile

tasks:
  - init: terraform init

vscode:
  extensions:
    # base extensions, TODO: abstract
    # I think we can install them in the base image?
    - coenraads.bracket-pair-colorizer-2
    # terraform-specific
    - hashicorp.terraform
