---
image:
  file: ".devcontainer/gitpod.Dockerfile"
tasks:
- init: terraform init
  command: zsh
vscode:
  extensions:
  - coenraads.bracket-pair-colorizer-2
  - oderwat.indent-rainbow
  - zainchen.json
  - equinusocio.vsc-material-theme
  - equinusocio.vsc-material-theme-icons
  - hashicorp.terraform
